services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      gunicorn hound_express_be.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hound_express_be.settings